### PR TITLE
Terminal Cloud API async: update return type

### LINKED ISSUE #1439: TerminalCloudAPI async response type
https://github.com/Adyen/adyen-node-api-library/blob/2a4c78b6d4371a9f4baf20dd9897ed8ecc2e01d1/src/__mocks__/terminalApi/async.ts#L20

While happy path does return an "ok" string, it would appear that failed requests return a payload. Could you please confirm this and adjust the return type accordingly? Thank you!

### PR DESCRIPTION
**Pull request by gcatanese**
The signature of the async method is incorrect
```
public async(terminalApiRequest: TerminalApiRequest): Promise<string> 
```
The API returns `ok` (string) unless there is an error. In that case the response is instead an instance of `TerminalApiResponse`.
This PR updates the signature of the method to
```
public async(terminalApiRequest: TerminalApiRequest): Promise<string | TerminalApiResponse>
```

### ⚠️ Breaking Change

- Changed return type of `TerminalCloudAPI.async()` from `Promise<string>` to `Promise<string | SaleToPOIRequest>`.
- Consumers must now check the type of the response before using it.

If you were assuming a `string` response, you now need to handle both `string` and `SaleToPOIRequest`:

```ts
const response = await terminalCloudAPI.async(paymentRequest);
// handle both `string` and `TerminalApiResponse`
if (typeof response === "string") {
  // Your previous logic
  ...
} else {
  // request failed: see details in the EventNotification object
  console.log("EventToNotify:", requestResponse.SaleToPOIRequest?.EventNotification?.EventToNotify);
  console.log("EventDetails:", requestResponse.SaleToPOIRequest?.EventNotification?.EventDetails);
}
```
Fix #1439

### CODE REVIEW

File: src/services/terminalCloudAPI.ts [hunk 1]
```diff
@@ -52,11 +52,22 @@ class TerminalCloudAPI extends Service {
...
-    public async(terminalApiRequest: TerminalApiRequest): Promise<string> {
+    /**
+     * Send an asynchronous payment request to the Terminal API.
+     *
+     * @param terminalApiRequest - The request to send.
+     * @returns A promise that resolves to "ok" if the request was successful, or a TerminalApiResponse if there is an error.
+     */
+    public async(terminalApiRequest: TerminalApiRequest): Promise<string | TerminalApiResponse> {
         const request = TerminalCloudAPI.setApplicationInfo(terminalApiRequest);
         return getJsonResponse<TerminalApiRequest>(this.terminalApiAsync, request);
```
[the remark this answers is not in the document]
Comment (gcatanese) [reply src/services/terminalCloudAPI.ts:63]: @gemini-code-assist should be addressed with the latest commits

File: src/helpers/getJsonResponse.ts [hunk 2]
```diff
@@ -19,8 +19,36 @@
 
 import Resource from "../services/resource";
 import { IRequest } from "../typings/requestOptions";
+import { TerminalApiResponse } from "../typings/terminal/models";
 
-async function getJsonResponse<T>(resource: Resource, jsonRequest: T | string, requestOptions?: IRequest.Options): Promise<string>;
+/**
+ * Sends a JSON request to the given resource and returns a string or a deserialized `TerminalApiResponse`.
+ * Used by Terminal API /sync method
```
Comment (naseemkullah) [inline src/helpers/getJsonResponse.ts]:
```suggestion
 * Used by Terminal API /async method
```

/sync or /async?

File: src/services/terminalCloudAPI.ts [hunk 3]
```diff
@@ -40,23 +40,34 @@ class TerminalCloudAPI extends Service {
...
     }
 
-    public async(terminalApiRequest: TerminalApiRequest): Promise<string> {
+    /**
+     * Send an asynchronous payment request to the Terminal API.
+     *
+     * @param terminalApiRequest - The request to send.
+     * @returns A promise that resolves to "ok" if the request was successful, or a TerminalApiResponse if there is an error.
+     */
+    public async(terminalApiRequest: TerminalApiRequest): Promise<string | TerminalApiResponse> {
```
Comment (naseemkullah) [inline src/services/terminalCloudAPI.ts:61]: 👍

File: src/helpers/getJsonResponse.ts (hunk 2 above)
Comment (gcatanese) [reply src/helpers/getJsonResponse.ts]: Oh yes, thanks for spotting this

**Review by Kwok-he-Chu — APPROVED** [review]
